#!/bin/bash
# Write _shader_manifest.lua: every shader .lua under _shader/, grouped by folder.
#
# main.lua discovers shaders with lfs.dir() over the resource directory. That
# works in the simulator, where the project is a directory of real files, but a
# packaged build (HTML5, Android, iOS) compiles every .lua into resource.car and
# the individual files are gone by the time the app runs — the listing comes back
# empty and every category is empty with it.
#
# So the packaged build gets the listing decided here, at build time. main.lua
# prefers this manifest when it is present and falls back to lfs.dir() when it is
# not, which keeps the simulator exactly as it was.
#
# Deliberately not committed: a checked-in copy would go stale the moment a
# shader is added and would silently win over the live directory listing.
#
# Usage: tools/gen-shader-manifest.sh [project-root]
set -euo pipefail

ROOT="${1:-$(cd "$(dirname "$0")/.." && pwd)}"
OUT="$ROOT/_shader_manifest.lua"

cd "$ROOT"

{
    echo "-- Generated by tools/gen-shader-manifest.sh — do not edit, do not commit."
    echo "-- Keys are the folder paths main.lua passes to file_get_match_sub()."
    echo "return {"
    find _shader -type d | LC_ALL=C sort | while read -r dir; do
        files=$(find "$dir" -maxdepth 1 -type f -name '*.lua' -printf '%f\n' | LC_ALL=C sort -f)
        [ -n "$files" ] || continue
        echo "    [\"$dir/\"] = {"
        while IFS= read -r f; do
            printf '        "%s",\n' "$f"
        done <<< "$files"
        echo "    },"
    done
    echo "}"
} > "$OUT"

echo "wrote $OUT ($(grep -c '\.lua",$' "$OUT") shaders)"
